export const fieldLabels: Record<string, string> = {
  browser: '浏览器',
  cost_time: '耗时',
  created_at: '创建时间',
  created_by: '创建人',
  credential_type: '客户端',
  cron_expression: 'Cron',
  data_scope: '数据范围',
  dict_id: '字典 ID',
  dict_name: '字典名称',
  dict_type: '字典类型',
  display_name: '显示名称',
  egress_id: '节点 ID',
  email: '邮箱',
  environment: '环境',
  expires_in: '剩余秒数',
  info_id: '日志 ID',
  invoke_target: '调用目标',
  ip_addr: 'IP 地址',
  job_group: '任务组',
  job_id: '任务 ID',
  job_name: '任务名称',
  last_seen_at: '最近心跳',
  login_at: '登录时间',
  menu_id: '权限 ID',
  menu_name: '权限名称',
  menu_type: '类型',
  msg: '消息',
  nick_name: '昵称',
  notice_id: '通知 ID',
  notice_title: '标题',
  notice_type: '类型',
  oper_id: '日志 ID',
  oper_ip: '操作 IP',
  oper_name: '操作人',
  operated_at: '操作时间',
  os: '系统',
  path: '路由',
  permissions: '权限',
  perms: '权限标识',
  postgres: 'PostgreSQL',
  public_endpoint: '公网入口',
  redis: 'Redis',
  request_method: '方法',
  role_id: '角色 ID',
  role_key: '角色标识',
  role_name: '角色名称',
  sea_orm: 'SeaORM',
  service: '服务',
  status: '状态',
  title: '操作',
  updated_at: '更新时间',
  user_id: '用户 ID',
  user_name: '用户',
};
