export const zhCNMonitorJobMessages = {
  "job.form.createTitle": "新增定时任务",
  "job.form.editTitle": "编辑定时任务",
  "job.form.description": "配置后台白名单定时任务。",
  "job.form.jobName": "任务名称",
  "job.form.jobNamePlaceholder": "请输入任务名称",
  "job.form.invokeTarget": "调用目标",
  "job.form.invokeTargetPlaceholder": "选择调用目标",
  "job.form.invokeTargetHelp": "仅支持服务端白名单内置任务，避免任意方法调用。",
  "job.form.cronExpression": "执行表达式",
  "job.form.cronExpressionPlaceholder": "@every 5m 或 */5 * * * *",
  "job.form.cronHelp":
    "支持 @hourly、@daily、@every 5m 或 5 字段 cron 表达式，按本地时间计算。",
  "job.form.misfirePolicy": "错过策略",
  "job.form.misfirePolicyPlaceholder": "选择策略",
  "job.form.concurrent": "并发执行",
  "job.form.concurrentPlaceholder": "选择并发策略",
  "job.form.status": "状态",
  "job.form.statusPlaceholder": "选择状态",
  "job.form.remark": "备注",
  "job.form.remarkPlaceholder": "请输入备注",
  "job.form.saveChanges": "保存修改",
  "job.form.validation.jobName": "请输入任务名称",
  "job.form.validation.invokeTarget": "请选择调用目标",
  "job.form.validation.cronExpression": "请输入执行表达式",
  "job.form.validation.invalidCron": "执行表达式不正确",

  "job.schedule.nextThreeRuns": "后续三次执行时间",
  "job.schedule.helpAria": "查看执行表达式说明",
  "job.schedule.helpTitle": "执行表达式怎么写",
  "job.schedule.helpDescription":
    "支持 @every、@hourly、@daily，也支持 5 字段 cron：分 时 日 月 周，按本地时间计算。",
  "job.schedule.copyExample": "复制{label}执行表达式",
  "job.schedule.copySuccess": "执行表达式已复制",
  "job.schedule.copyFailed": "复制失败，请手动复制",
  "job.schedule.example.every5m": "每 5 分钟",
  "job.schedule.example.hourly": "每小时",
  "job.schedule.example.daily2": "每天 2 点",
  "job.schedule.example.weekday9": "工作日 9 点",
  "job.schedule.example.monthly1": "每月 1 日 3 点",
  "job.schedule.error.empty": "请输入执行表达式",
  "job.schedule.error.everyUnsupported":
    "@every 仅支持 s、m、h，例如 @every 5m",
  "job.schedule.error.everyPositive": "@every 时间间隔必须大于 0",
  "job.schedule.error.fieldCount": "cron 表达式需要 5 个字段",
  "job.schedule.error.fieldEmpty": "cron 字段不能为空",
  "job.schedule.error.noValues": "cron 字段没有可执行值",
  "job.schedule.error.stepPositive": "cron 步长必须大于 0",
  "job.schedule.error.outOfRange": "cron 字段超出允许范围",
  "job.schedule.error.noNext": "未能在有效范围内计算下次执行时间",

  "job.detail.fallbackTitle": "任务详情",
  "job.detail.description": "查看定时任务配置与后续执行时间。",
  "job.detail.basicInfo": "基本信息",
  "job.detail.nextRuns": "后续执行",
  "job.detail.invokeTarget": "调用目标",
  "job.detail.cronExpression": "执行表达式",
  "job.detail.status": "状态",
  "job.detail.misfirePolicy": "错过策略",
  "job.detail.concurrent": "并发执行",
  "job.detail.createdAt": "创建时间",
  "job.detail.remark": "备注",

  "job.runDetail.title": "执行记录详情",
  "job.runDetail.description": "查看单次任务执行的输入、状态与输出结果。",
  "job.runDetail.runTitle": "执行 #{id}",
  "job.runDetail.jobName": "任务名称",
  "job.runDetail.trigger": "触发方式",
  "job.runDetail.invokeTarget": "调用目标",
  "job.runDetail.duration": "耗时",
  "job.runDetail.startedAt": "开始时间",
  "job.runDetail.endedAt": "结束时间",
  "job.runDetail.message": "执行消息",
  "job.runDetail.exception": "异常信息",
  "job.runDetail.recorded": "已记录",

  "job.log.title": "{name} 执行记录",
  "job.log.fallbackTitle": "执行记录",
  "job.log.description": "查看定时任务最近执行结果，每一条记录对应一次 run。",
  "job.log.statusFilter": "调度日志状态筛选",
  "job.log.searchPlaceholder": "搜索任务、调用目标、执行消息...",
  "job.log.emptyTitle": "暂无执行记录",
  "job.log.emptyDescription": "当前任务还没有执行记录。",
  "job.log.viewDetail": "查看执行记录详情",
  "job.log.all": "全部",
  "job.log.success": "成功",
  "job.log.failed": "失败",

  "job.option.status.enabled": "启用",
  "job.option.status.disabled": "停用",
  "job.option.misfire.now": "立即执行",
  "job.option.misfire.once": "执行一次",
  "job.option.misfire.skip": "放弃执行",
  "job.option.concurrent.disallow": "禁止并发",
  "job.option.concurrent.allow": "允许并发",
  "job.option.invoke.healthcheck": "健康检查",
  "job.option.invoke.cleanupLogs": "清理任务日志",
  "job.option.invoke.noop": "空任务",
  "job.option.trigger.manual": "手动",
  "job.option.trigger.schedule": "自动",
  "job.message.cleanup": "已清理 {count} 条 30 天前的任务日志",
  "job.message.noop": "空任务已完成",
  "job.message.readinessPassed": "健康检查通过",
  "job.message.readinessFailed": "健康检查失败",
  "job.message.cleanupFailed": "任务日志清理失败",
  "job.message.postgresUnavailable": "PostgreSQL 不可用",
  "job.message.unsupportedInvokeTarget": "不支持的调用目标",
  "job.message.skipped": "上一轮仍在执行，已跳过本次任务",
  "job.message.waitingReadiness": "等待健康检查返回。",
} as const

export type MonitorJobMessageKey = keyof typeof zhCNMonitorJobMessages
