export const monitorMessages: Record<string, string> = {
  "common.empty": "暂无",
  "common.metricSeparator": "，",
  "common.unknownServerError": "服务器返回了未知错误。",
  "duration.day": "天",
  "duration.hour": "小时",
  "duration.minute": "分钟",
  "duration.second": "秒",
  "health.connection.closed": "已断开",
  "health.connection.connecting": "连接中",
  "health.connection.live": "实时",
  "health.connection.reconnecting": "重连中",
  "health.cpu.load": "负载",
  "health.cpu.wait": "等待 CPU 负载返回。",
  "health.description": "聚焦后台服务器程序，CPU / 内存 / 存储。",
  "health.error.title": "健康检查返回错误",
  "health.memory.label": "内存",
  "health.memory.limit": "限制",
  "health.memory.processUsage": "进程占用",
  "health.memory.wait": "等待内存指标返回。",
  "health.process.cpuTime": "CPU 时间",
  "health.process.cpuUsage": "CPU 占用",
  "health.process.dataMemory": "Data 内存",
  "health.process.deployment": "部署信息",
  "health.process.description":
    "所有运行指标均来自当前 one-browser-server 后端进程。",
  "health.process.executable": "可执行文件",
  "health.process.fdCount": "FD 数",
  "health.process.fdLimit": "FD 上限",
  "health.process.fdUsage": "FD 使用率",
  "health.process.memoryFootprint": "内存足迹",
  "health.process.memoryShare": "内存占比",
  "health.process.metrics": "运行指标",
  "health.process.peakRss": "峰值 RSS",
  "health.process.rssMemory": "RSS 内存",
  "health.process.runtime": "运行时",
  "health.process.rustVersion": "Rust 版本",
  "health.process.startedAt": "启动时间",
  "health.process.systemCpu": "内核态 CPU",
  "health.process.threads": "线程数",
  "health.process.title": "后端进程",
  "health.process.uptime": "进程运行时长",
  "health.process.userCpu": "用户态 CPU",
  "health.process.version": "版本号",
  "health.process.virtualMemory": "虚拟内存",
  "health.reconnect": "重新连接",
  "health.server.arch": "服务器系统",
  "health.server.bootTime": "服务器开机时间",
  "health.server.currentTime": "服务器时间",
  "health.server.descriptionPrefix":
    "服务器级别的信息（区别于进程运行时），最近更新：",
  "health.server.hostname": "服务器名称",
  "health.server.title": "服务器与版本",
  "health.server.uptime": "服务器运行时长",
  "health.storage.label": "存储",
  "health.storage.wait": "等待存储指标返回。",
  "health.stream.title": "实时连接状态",
  "health.title": "服务监控",
  "online.columns.browser": "浏览器",
  "online.columns.credentialType": "登录类型",
  "online.columns.expiresIn": "剩余有效期",
  "online.columns.ipAddress": "登录地址",
  "online.columns.loginAccount": "登录账号",
  "online.columns.loginTime": "登录时间",
  "online.columns.os": "操作系统",
  "online.credential.desktopApp": "桌面端",
  "online.credential.web": "Web",
  "online.empty.description": "当前没有可显示的登录会话。",
  "online.empty.title": "暂无在线用户",
  "online.expired": "已过期",
  "online.forceLogout.action": "强制下线",
  "online.forceLogout.aria": "强退 {name}",
  "online.forceLogout.description":
    "确认强制“{name}”下线吗？该操作会立即删除当前会话令牌。",
  "online.forceLogout.success": "{name} 已强制下线",
  "online.forceLogout.title": "强制用户下线",
  "online.forceLogout.tokenDeleted": "该会话令牌已从 Redis 中删除。",
  "online.refresh.description": "已获取后台最新数据。",
  "online.refresh.success": "在线用户列表已刷新",
  "online.search.placeholder": "搜索账号、IP、浏览器、系统、类型...",
  "time.justNow": "刚刚",
}
