export const enUSAdminExtraMessages: Record<string, string> = {
  个人账号: "Account",
  账号: "Account",
  账号设置: "Account settings",
  个人信息: "Profile",
  修改密码: "Change password",
  当前密码: "Current password",
  新密码: "New password",
  确认新密码: "Confirm password",
  密码强度: "Password strength",
  未输入: "Empty",
  偏弱: "Weak",
  一般: "Fair",
  较强: "Strong",
  强: "Strong",
  清空: "Clear",
  保存密码: "Save password",
  保存修改: "Save changes",
  查看头像大图: "Preview avatar",
  上传头像: "Upload avatar",
  复制用户名: "Copy username",
  头像预览: "Avatar preview",
  修改头像: "Change avatar",
  待裁剪头像: "Avatar to crop",
  请选择图片: "Select an image",
  请选择头像图片: "Select an avatar image",
  选择图片: "Select image",
  缩小: "Zoom out",
  放大: "Zoom in",
  头像缩放: "Avatar zoom",
  预览: "Preview",
  提交: "Submit",
  重置: "Reset",
  取消: "Cancel",
  昵称不能为空: "Nickname is required",
  "昵称不能超过 64 个字符": "Nickname cannot exceed 64 characters",
  邮箱格式不正确: "Invalid email address",
  "手机号不能超过 32 个字符": "Phone number cannot exceed 32 characters",
  "头像地址不能超过 255 个字符": "Avatar URL cannot exceed 255 characters",
  账号信息已保存: "Account information saved",
  账号信息保存失败: "Failed to save account information",
  头像已更新: "Avatar updated",
  头像上传失败: "Failed to upload avatar",
  "请选择 jpg、png、webp 或 gif 图片": "Select a jpg, png, webp, or gif image",
  "头像不能超过 5 MB": "Avatar must be 5 MB or smaller",
  暂无可复制的用户名: "No username to copy",
  用户名已复制: "Username copied",
  "复制失败，请稍后重试": "Copy failed. Try again later.",
  "维护当前账号的头像、昵称和联系信息。":
    "Manage the avatar, nickname, and contact information for this account.",
  "头像、昵称和联系方式保存后立即生效。":
    "Avatar, nickname, and contact information take effect after saving.",
  "当前资料有修改，保存后会同步到当前账号。":
    "Profile changes will be synced to the current account after saving.",
  "当前资料已和服务器保持同步。":
    "Profile information is already in sync with the server.",
  请输入当前密码: "Enter current password",
  "新密码至少需要 10 位": "New password must be at least 10 characters",
  "新密码不能超过 128 位": "New password cannot exceed 128 characters",
  请再次输入新密码: "Confirm the new password",
  两次输入的新密码不一致: "The new passwords do not match",
  新密码不能和当前密码相同:
    "The new password cannot be the same as the current password",
  登录密码已更新: "Password updated",
  密码修改失败: "Failed to change password",
  "修改后请使用新密码登录当前账号。":
    "Use the new password next time you sign in to this account.",
  "至少 10 位，建议包含大小写字母、数字或符号。":
    "Use at least 10 characters. Uppercase, lowercase, numbers, or symbols are recommended.",
  "保存后服务端会校验当前密码是否正确。":
    "The server will verify the current password when saving.",
  隐藏密码: "Hide password",
  显示密码: "Show password",
  "输入新密码后显示强度。":
    "Password strength appears after you enter a new password.",
  "建议至少 10 位，并加入大小写、数字或符号。":
    "Use at least 10 characters and add letter case, numbers, or symbols.",
  "可以继续增加长度或更多字符类型。":
    "Add more length or character types to improve it.",
  "强度不错，继续增加长度会更稳。":
    "Good strength. More length makes it safer.",
  "强度良好，请妥善保存新密码。": "Strong password. Keep it safe.",
  "选择图片后裁剪为方形头像，提交后才会上传。":
    "Crop the image into a square avatar. It uploads only after submission.",
  "拖动图片调整位置，使用缩放控制头像范围。":
    "Drag the image to adjust position and use zoom to control the avatar area.",
  头像图片加载失败: "Failed to load avatar image",
  当前浏览器不支持头像裁剪: "This browser does not support avatar cropping",
  头像裁剪失败: "Failed to crop avatar",
  "{title} 的头像": "{title}'s avatar",

  全部: "All",
  成功: "Success",
  失败: "Failed",
  系统: "System",
  详情: "Details",
  复制: "Copy",
  已复制: "Copied",
  "复制失败，请手动选择文本复制。":
    "Copy failed. Select the text manually to copy.",
  操作模块: "Module",
  业务类型: "Business type",
  请求方式: "Method",
  操作人员: "Operator",
  操作地址: "IP address",
  请求地址: "Request address",
  请求路径: "Request path",
  "耗时(ms)": "Duration(ms)",
  消耗时间: "Duration",
  毫秒: "ms",
  操作时间: "Operated at",
  操作方法: "Handler",
  所属部门: "Department",
  登录账号: "Login account",
  登录地址: "Login address",
  浏览器: "Browser",
  操作系统: "Operating system",
  提示消息: "Message",
  登录时间: "Login time",
  操作日志详情: "Operation log details",
  登录日志详情: "Login log details",
  "查看本次后台操作的请求、参数和执行结果。":
    "View the request, parameters, and result of this backend operation.",
  "查看本次登录的账号、客户端和执行状态。":
    "View the account, client, and status for this sign-in.",
  概要: "Summary",
  请求参数: "Request parameters",
  返回参数: "Response parameters",
  异常信息: "Exception",
  "加载详情中...": "Loading details...",
  "详情加载失败，请关闭后重试。":
    "Failed to load details. Close this dialog and try again.",
  "归属地查询中...": "Looking up location...",
  归属地查询失败: "Location lookup failed",
  "(无数据)": "(No data)",
  "搜索账号、IP、浏览器、消息...": "Search account, IP, browser, message...",
  暂无登录日志: "No login logs",
  "系统还没有记录到任何登录访问。": "No sign-in access has been recorded yet.",
  登录日志状态筛选: "Login log status filter",
  "搜索模块、人员、路径、IP...": "Search module, operator, path, IP...",
  暂无操作日志: "No operation logs",
  "系统还没有记录到任何后台操作。":
    "No backend operations have been recorded yet.",
  操作日志状态筛选: "Operation log status filter",

  字典数据: "Dictionary data",
  字典列表: "Dictionary data",
  "{name} 字典列表": "{name} dictionary data",
  "搜索字典标签、键值...": "Search dictionary label or value...",
  暂无字典数据: "No dictionary data",
  "当前字典类型下还没有字典数据。":
    "There is no data under this dictionary type yet.",
  新增字典数据: "Create dictionary data",
  字典数据状态: "Dictionary data status",
  字典数据暂不支持拖拽排序: "Dictionary data does not support drag sorting yet",
  缺少字典类型: "Missing dictionary type",
  拖拽调整排序: "Drag to reorder",
  收起节点: "Collapse node",
  展开节点: "Expand node",
  选择上级部门: "Select parent department",
  "正在加载部门...": "Loading departments...",
  暂无可选部门: "No departments available",
  收起部门: "Collapse department",
  展开部门: "Expand department",
  "展开/折叠": "Expand/collapse",
  "全选/全不选": "Select/deselect all",
  父子联动: "Link parent and child",
  "正在加载权限...": "Loading permissions...",
  暂无权限: "No permissions",
  收起权限节点: "Collapse permission node",
  展开权限节点: "Expand permission node",
  顶级菜单: "Top-level menu",
  "搜索权限...": "Search permissions...",
  没有匹配的权限: "No matching permissions",
  选择菜单图标: "Select menu icon",
  当前: "Current",
  搜索图标名称或标识: "Search icon name or key",
  没有匹配的图标: "No matching icons",
  换一个关键词或分类试试: "Try another keyword or category.",
  当前显示: "Showing",
  个: "items",
  共: "of",
  上一页: "Previous",
  下一页: "Next",
  "正在加载角色...": "Loading roles...",
  "正在加载岗位...": "Loading posts...",
  请选择角色: "Select roles",
  请选择岗位: "Select posts",
  "角色加载失败，请稍后重试。": "Failed to load roles. Try again later.",
  "岗位加载失败，请稍后重试。": "Failed to load posts. Try again later.",
  常用: "Common",
  组织: "Organization",
  内容: "Content",
  工具: "Tools",
  主页: "Home",
  设置: "Settings",
  配置: "Configuration",
  系统配置: "System config",
  侧栏: "Sidebar",
  分层: "Layers",
  流程: "Workflow",
  标签: "Tag",
  安全: "Security",
  身份认证: "Authentication",
  登录: "Login",
  审核: "Audit",
  参数: "Parameters",
  系统文件: "System files",
  用户验证: "User verification",
  用户配置: "User config",
  职位: "Position",
  身份卡: "ID card",
  数据: "Data",
  数据服务: "Data service",
  文档: "Documents",
  日志文档: "Log documents",
  树列表: "Tree list",
  清单: "Checklist",
  数据表: "Data table",
  展开目录: "Expand directory",
  归档: "Archive",
  包: "Package",
  盒子: "Box",
  资源包: "Packages",
  服务器: "Server",
  活动: "Activity",
  仪表盘: "Dashboard",
  性能: "Performance",
  存储: "Storage",
  网络: "Network",
  日志: "Logs",
  历史: "History",
  计划任务: "Scheduled jobs",
  日历: "Calendar",
  全局: "Global",
  插件: "Plugins",
  检索: "Search",
  上传: "Upload",
  下载: "Download",
  支付: "Payment",
  统计: "Statistics",
  柱状图: "Bar chart",
  报表: "Reports",
}
