export const monitorMessages: Record<string, string> = {
  "common.empty": "-",
  "common.metricSeparator": ", ",
  "common.unknownServerError": "The server returned an unknown error.",
  "duration.day": "d",
  "duration.hour": "h",
  "duration.minute": "m",
  "duration.second": "s",
  "health.connection.closed": "Disconnected",
  "health.connection.connecting": "Connecting",
  "health.connection.live": "Live",
  "health.connection.reconnecting": "Reconnecting",
  "health.cpu.load": "Load",
  "health.cpu.wait": "Waiting for CPU load metrics.",
  "health.description":
    "Monitor the backend server process, CPU, memory, and storage.",
  "health.error.title": "Health check returned an error",
  "health.memory.label": "Memory",
  "health.memory.limit": "Limit",
  "health.memory.processUsage": "Process usage",
  "health.memory.wait": "Waiting for memory metrics.",
  "health.process.cpuTime": "CPU time",
  "health.process.cpuUsage": "CPU usage",
  "health.process.dataMemory": "Data memory",
  "health.process.deployment": "Deployment",
  "health.process.description":
    "All runtime metrics come from the current one-browser-server backend process.",
  "health.process.executable": "Executable",
  "health.process.fdCount": "FD count",
  "health.process.fdLimit": "FD limit",
  "health.process.fdUsage": "FD usage",
  "health.process.memoryFootprint": "Memory footprint",
  "health.process.memoryShare": "Memory share",
  "health.process.metrics": "Runtime metrics",
  "health.process.peakRss": "Peak RSS",
  "health.process.rssMemory": "RSS memory",
  "health.process.runtime": "Runtime",
  "health.process.rustVersion": "Rust version",
  "health.process.startedAt": "Started at",
  "health.process.systemCpu": "System CPU",
  "health.process.threads": "Threads",
  "health.process.title": "Backend process",
  "health.process.uptime": "Process uptime",
  "health.process.userCpu": "User CPU",
  "health.process.version": "Version",
  "health.process.virtualMemory": "Virtual memory",
  "health.reconnect": "Reconnect",
  "health.server.arch": "Server OS",
  "health.server.bootTime": "Server boot time",
  "health.server.currentTime": "Server time",
  "health.server.descriptionPrefix":
    "Server-level information separate from the runtime process. Last updated: ",
  "health.server.hostname": "Server name",
  "health.server.title": "Server and version",
  "health.server.uptime": "Server uptime",
  "health.storage.label": "Storage",
  "health.storage.wait": "Waiting for storage metrics.",
  "health.stream.title": "Realtime connection status",
  "health.title": "Service monitor",
  "online.columns.browser": "Browser",
  "online.columns.expiresIn": "Remaining TTL",
  "online.columns.ipAddress": "Login address",
  "online.columns.loginAccount": "Login account",
  "online.columns.loginTime": "Login time",
  "online.columns.os": "Operating system",
  "online.empty.description": "There are no active login sessions to display.",
  "online.empty.title": "No online users",
  "online.expired": "Expired",
  "online.forceLogout.action": "Force offline",
  "online.forceLogout.aria": "Force {name} offline",
  "online.forceLogout.description":
    "Force “{name}” offline? This immediately removes the current session token.",
  "online.forceLogout.success": "{name} has been forced offline",
  "online.forceLogout.title": "Force user offline",
  "online.forceLogout.tokenDeleted":
    "The session token has been removed from Redis.",
  "online.refresh.description": "Fetched the latest online users.",
  "online.refresh.success": "Online users refreshed",
  "online.search.placeholder": "Search account, IP, browser, or OS...",
  "time.justNow": "just now",
}
