import type { MonitorJobMessageKey } from "@/local/zh-CN/monitor-job"

export const enUSMonitorJobMessages: Record<MonitorJobMessageKey, string> = {
  "job.form.createTitle": "Create scheduled job",
  "job.form.editTitle": "Edit scheduled job",
  "job.form.description": "Configure a whitelisted backend scheduled job.",
  "job.form.jobName": "Job name",
  "job.form.jobNamePlaceholder": "Enter job name",
  "job.form.invokeTarget": "Invoke target",
  "job.form.invokeTargetPlaceholder": "Select invoke target",
  "job.form.invokeTargetHelp":
    "Only built-in server-side whitelisted jobs are supported to avoid arbitrary method calls.",
  "job.form.cronExpression": "Cron expression",
  "job.form.cronExpressionPlaceholder": "@every 5m or */5 * * * *",
  "job.form.cronHelp":
    "Supports @hourly, @daily, @every 5m, or 5-field cron expressions. Times are calculated in local time.",
  "job.form.misfirePolicy": "Misfire policy",
  "job.form.misfirePolicyPlaceholder": "Select policy",
  "job.form.concurrent": "Concurrent execution",
  "job.form.concurrentPlaceholder": "Select concurrency policy",
  "job.form.status": "Status",
  "job.form.statusPlaceholder": "Select status",
  "job.form.remark": "Remark",
  "job.form.remarkPlaceholder": "Enter remark",
  "job.form.saveChanges": "Save changes",
  "job.form.validation.jobName": "Enter job name",
  "job.form.validation.invokeTarget": "Select invoke target",
  "job.form.validation.cronExpression": "Enter cron expression",
  "job.form.validation.invalidCron": "Cron expression is invalid",

  "job.schedule.nextThreeRuns": "Next three run times",
  "job.schedule.helpAria": "View cron expression help",
  "job.schedule.helpTitle": "How to write the cron expression",
  "job.schedule.helpDescription":
    "Supports @every, @hourly, @daily, and 5-field cron: minute hour day month weekday. Times are calculated in local time.",
  "job.schedule.copyExample": "Copy {label} cron expression",
  "job.schedule.copySuccess": "Cron expression copied",
  "job.schedule.copyFailed": "Copy failed. Please copy manually.",
  "job.schedule.example.every5m": "Every 5 minutes",
  "job.schedule.example.hourly": "Hourly",
  "job.schedule.example.daily2": "Daily at 2:00",
  "job.schedule.example.weekday9": "Weekdays at 9:00",
  "job.schedule.example.monthly1": "Monthly on day 1 at 3:00",
  "job.schedule.error.empty": "Enter cron expression",
  "job.schedule.error.everyUnsupported":
    "@every supports only s, m, or h, for example @every 5m",
  "job.schedule.error.everyPositive": "@every interval must be greater than 0",
  "job.schedule.error.fieldCount": "Cron expression requires 5 fields",
  "job.schedule.error.fieldEmpty": "Cron field cannot be empty",
  "job.schedule.error.noValues": "Cron field has no executable values",
  "job.schedule.error.stepPositive": "Cron step must be greater than 0",
  "job.schedule.error.outOfRange": "Cron field is out of range",
  "job.schedule.error.noNext":
    "Unable to calculate the next run time within the valid range",

  "job.detail.fallbackTitle": "Job details",
  "job.detail.description":
    "View scheduled job configuration and upcoming run times.",
  "job.detail.basicInfo": "Basic information",
  "job.detail.nextRuns": "Upcoming runs",
  "job.detail.invokeTarget": "Invoke target",
  "job.detail.cronExpression": "Cron expression",
  "job.detail.status": "Status",
  "job.detail.misfirePolicy": "Misfire policy",
  "job.detail.concurrent": "Concurrent execution",
  "job.detail.createdAt": "Created at",
  "job.detail.remark": "Remark",

  "job.runDetail.title": "Run details",
  "job.runDetail.description":
    "View the input, status, and output for a single job run.",
  "job.runDetail.runTitle": "Run #{id}",
  "job.runDetail.jobName": "Job name",
  "job.runDetail.trigger": "Trigger",
  "job.runDetail.invokeTarget": "Invoke target",
  "job.runDetail.duration": "Duration",
  "job.runDetail.startedAt": "Started at",
  "job.runDetail.endedAt": "Ended at",
  "job.runDetail.message": "Run message",
  "job.runDetail.exception": "Exception",
  "job.runDetail.recorded": "Recorded",

  "job.log.title": "{name} run logs",
  "job.log.fallbackTitle": "Run logs",
  "job.log.description":
    "View recent scheduled job results. Each row corresponds to one run.",
  "job.log.statusFilter": "Scheduler log status filter",
  "job.log.searchPlaceholder": "Search job, invoke target, run message...",
  "job.log.emptyTitle": "No run logs",
  "job.log.emptyDescription": "This job has no run logs yet.",
  "job.log.viewDetail": "View run log details",
  "job.log.all": "All",
  "job.log.success": "Success",
  "job.log.failed": "Failed",

  "job.option.status.enabled": "Enabled",
  "job.option.status.disabled": "Disabled",
  "job.option.misfire.now": "Run immediately",
  "job.option.misfire.once": "Run once",
  "job.option.misfire.skip": "Skip run",
  "job.option.concurrent.disallow": "Disallow overlap",
  "job.option.concurrent.allow": "Allow overlap",
  "job.option.invoke.healthcheck": "Health check",
  "job.option.invoke.cleanupLogs": "Clean job logs",
  "job.option.invoke.noop": "No-op job",
  "job.option.trigger.manual": "Manual",
  "job.option.trigger.schedule": "Schedule",
  "job.message.cleanup": "Removed {count} job logs older than 30 days",
  "job.message.noop": "No-op job completed",
  "job.message.readinessPassed": "Health check passed",
  "job.message.readinessFailed": "Health check failed",
  "job.message.cleanupFailed": "Job log cleanup failed",
  "job.message.postgresUnavailable": "PostgreSQL unavailable",
  "job.message.unsupportedInvokeTarget": "Unsupported invoke target",
  "job.message.skipped":
    "Previous run is still executing. This run was skipped.",
  "job.message.waitingReadiness": "Waiting for the health check response.",
}
