export const enUSTextMessages: Record<string, string> = {
  首页: "Home",
  用户管理: "User management",
  角色管理: "Role management",
  权限管理: "Permission management",
  字典管理: "Dictionary management",
  通知管理: "Notice management",
  操作日志: "Operation logs",
  登录日志: "Login logs",
  服务监控: "Service monitor",
  在线用户: "Online users",
  定时任务: "Scheduled jobs",
  个人账号: "Account",
  系统: "System",
  系统管理: "System management",
  系统日志: "System logs",
  系统监控: "System monitor",
  浏览器管理: "Browser management",
  环境管理: "Environment management",
  代理管理: "Proxy management",
  成员管理: "Member management",

  用户: "User",
  角色: "Role",
  权限: "Permission",
  字典类型: "Dictionary type",
  字典数据: "Dictionary data",
  通知: "Notice",
  公告: "Announcement",
  账号: "Account",
  用户角色: "User roles",
  环境: "Environment",
  代理: "Proxy",
  成员: "Member",
  团队: "Team",
  团队角色: "Team role",
  分组: "Group",
  环境名称: "Environment name",
  代理名称: "Proxy name",
  出口IP: "Exit IP",
  "出口 IP": "Exit IP",
  检测状态: "Check status",
  关联环境: "Linked environments",
  最近打开: "Last opened",
  最近活跃: "Last active",
  浏览器环境: "Browser environment",
  已绑定代理: "Bound proxy",
  未绑定代理: "No proxy",
  待接入: "Pending integration",
  检测通过: "Check passed",
  未检测: "Unchecked",
  团队管理员: "Team admin",
  团队成员: "Team member",

  全部: "All",
  成功: "Success",
  失败: "Failed",
  启用: "Enabled",
  停用: "Disabled",
  禁用: "Disable",
  已启用: "Enabled",
  已禁用: "Disabled",
  男: "Male",
  女: "Female",
  不愿透露: "Prefer not to say",
  全部数据: "All data",
  仅本人数据: "Self only",
  目录: "Directory",
  菜单: "Menu",
  按钮: "Button",
  显示: "Visible",
  隐藏: "Hidden",
  是: "Yes",
  否: "No",
  默认: "Default",
  状态: "Status",
  备注: "Remark",
  创建时间: "Created at",
  更新时间: "Updated at",
  创建人: "Created by",
  排序: "Sort",
  操作: "Actions",
  详情: "Details",
  保存: "Save",
  创建: "Create",
  取消: "Cancel",
  删除: "Delete",
  批量删除: "Bulk delete",
  刷新: "Refresh",
  新增: "Create",
  修改: "Edit",
  编辑: "Edit",
  授权: "Authorize",
  其他: "Other",
  重置密码: "Reset password",
  分配角色: "Assign roles",
  重新分配角色: "Reassign roles",

  用户名: "Username",
  用户昵称: "Nickname",
  昵称: "Nickname",
  用户名称: "Username",
  用户密码: "Password",
  手机号码: "Phone number",
  手机号: "Phone",
  邮箱: "Email",
  性别: "Gender",
  用户性别: "Gender",
  最近登录: "Last login",
  角色名称: "Role name",
  权限标识: "Permission key",
  权限字符: "Permission key",
  角色顺序: "Role order",
  数据范围: "Data scope",
  权限范围: "Permission scope",
  权限类型: "Permission type",
  权限名称: "Permission name",
  上级权限: "Parent permission",
  图标: "Icon",
  路由路径: "Route path",
  可见状态: "Visibility",
  负责人: "Owner",
  联系电话: "Phone",
  电话: "Phone",
  字典代码: "Dictionary code",
  字典标签: "Dictionary label",
  字典键值: "Dictionary value",
  字典列表: "Dictionary data",
  列表: "List",
  "{name} 字典列表": "{name} dictionary data",
  "搜索字典标签、键值...": "Search dictionary label or value...",
  暂无字典数据: "No dictionary data",
  "当前字典类型下还没有字典数据。":
    "There is no data under this dictionary type yet.",
  新增字典数据: "Create dictionary data",
  字典数据状态: "Dictionary data status",
  字典数据暂不支持拖拽排序: "Dictionary data does not support drag sorting yet",
  缺少字典类型: "Missing dictionary type",
  通知标题: "Notice title",
  通知类型: "Notice type",
  通知内容: "Notice content",

  操作模块: "Module",
  业务类型: "Business type",
  请求方式: "Method",
  操作人员: "Operator",
  操作地址: "IP address",
  请求地址: "Request address",
  请求路径: "Request path",
  "耗时(ms)": "Duration(ms)",
  消耗时间: "Duration",
  毫秒: "ms",
  操作时间: "Operated at",
  操作方法: "Handler",
  登录账号: "Login account",
  登录地址: "Login address",
  浏览器: "Browser",
  操作系统: "Operating system",
  提示消息: "Message",
  登录时间: "Login time",
  剩余有效期: "Remaining TTL",
  已过期: "Expired",
  操作日志详情: "Operation log details",
  登录日志详情: "Login log details",
  查看本次后台操作的请求参数和执行结果:
    "View the request, parameters, and result of this backend operation.",
  "查看本次后台操作的请求、参数和执行结果。":
    "View the request, parameters, and result of this backend operation.",
  查看本次登录的账号客户端和执行状态:
    "View the account, client, and status for this sign-in.",
  "查看本次登录的账号、客户端和执行状态。":
    "View the account, client, and status for this sign-in.",
  概要: "Summary",
  请求参数: "Request parameters",
  返回参数: "Response parameters",
  异常信息: "Exception",
  "加载详情中...": "Loading details...",
  "详情加载失败，请关闭后重试。":
    "Failed to load details. Close this dialog and try again.",
  复制: "Copy",
  "归属地查询中...": "Looking up location...",
  归属地查询失败: "Location lookup failed",
  "(无数据)": "(No data)",
  已复制: "Copied",
  "复制失败，请手动选择文本复制。":
    "Copy failed. Select the text manually to copy.",
  "搜索账号、IP、浏览器、消息...": "Search account, IP, browser, message...",
  暂无登录日志: "No login logs",
  系统还没有记录到任何登录访问: "No sign-in access has been recorded yet.",
  "系统还没有记录到任何登录访问。": "No sign-in access has been recorded yet.",
  登录日志状态筛选: "Login log status filter",
  "搜索模块、人员、路径、IP...": "Search module, operator, path, IP...",
  暂无操作日志: "No operation logs",
  系统还没有记录到任何后台操作: "No backend operations have been recorded yet.",
  "系统还没有记录到任何后台操作。":
    "No backend operations have been recorded yet.",
  操作日志状态筛选: "Operation log status filter",
  "搜索账号、IP、浏览器、系统...": "Search account, IP, browser, OS...",
  暂无在线用户: "No online users",
  "当前没有可显示的登录会话。": "There are no sign-in sessions to display.",
  该会话令牌已从Redis中删除: "The session token has been deleted from Redis.",
  "该会话令牌已从 Redis 中删除。":
    "The session token has been deleted from Redis.",
  强制用户下线: "Force user offline",
  强制下线: "Force offline",

  当前用户: "Current user",
  运行环境: "Environment",
  服务状态: "Service status",
  依赖状态: "Dependency status",
  核心资源: "Core resources",
  系统管理总览: "System overview",
  常用入口: "Quick entries",
  快捷操作: "Quick actions",
  近期数据: "Recent data",
  最近创建的资源: "Recently created resources",
  服务健康: "Service health",
  依赖健康: "Dependency health",
  运行状态: "Runtime status",
  服务器与版本: "Server and version",
  "服务器级别的信息（区别于进程运行时），最近更新：":
    "Server-level information (separate from process runtime), last updated: ",
  服务器名称: "Server name",
  服务器系统: "Server OS",
  服务器运行时长: "Server uptime",
  服务器开机时间: "Server boot time",
  服务器时间: "Server time",
  后端进程: "Backend process",
  "所有运行指标均来自当前 one-browser-server 后端进程。":
    "All runtime metrics come from the current one-browser-server backend process.",
  部署信息: "Deployment",
  版本号: "Version",
  可执行文件: "Executable",
  启动时间: "Started at",
  进程运行时长: "Process uptime",
  运行时: "Runtime",
  "Rust 版本": "Rust version",
  运行指标: "Runtime metrics",
  "CPU 占用": "CPU usage",
  "CPU 时间": "CPU time",
  "用户态 CPU": "User CPU",
  "内核态 CPU": "Kernel CPU",
  "RSS 内存": "RSS memory",
  内存占比: "Memory share",
  "峰值 RSS": "Peak RSS",
  内存足迹: "Memory footprint",
  虚拟内存: "Virtual memory",
  "Data 内存": "Data memory",
  线程数: "Threads",
  "FD 数": "FD count",
  "FD 上限": "FD limit",
  "FD 使用率": "FD usage",
  内存: "Memory",
  存储: "Storage",
  负载: "Load",
  限制: "Limit",
  进程占用: "Process usage",
  "等待 CPU 负载返回。": "Waiting for CPU load metrics.",
  "等待内存指标返回。": "Waiting for memory metrics.",
  "等待存储指标返回。": "Waiting for storage metrics.",
  "聚焦后台服务器程序，CPU / 内存 / 存储。":
    "Monitor backend server CPU, memory, and storage.",
  重新连接: "Reconnect",
  健康检查返回错误: "Health check returned an error",
  实时连接状态: "Realtime connection status",
  实时: "Live",
  连接中: "Connecting",
  重连中: "Reconnecting",
  已断开: "Disconnected",
  "服务器返回了未知错误。": "The server returned an unknown error.",
  检查中: "Checking",
  健康: "Healthy",
  注意: "Warning",
  降级: "Degraded",
  错误: "Error",
  加载中: "Loading",
  正常: "Normal",
  未登录: "Not signed in",
  后台账号: "Admin accounts",
  权限角色: "Permission roles",
  菜单与按钮权限: "Menus and button permissions",
  字典定义: "Dictionary definitions",
  通知公告: "Notices",
  健康检查: "Health check",
  定时任务已创建: "Scheduled job created",
  定时任务已更新: "Scheduled job updated",
  任务已启用: "Job enabled",
  任务已停用: "Job disabled",
  定时任务状态筛选: "Scheduled job status filter",
  "搜索任务名称、调用目标、表达式...":
    "Search job name, target, or expression...",
  暂无定时任务: "No scheduled jobs",
  "当前还没有配置任何后台定时任务。":
    "No backend scheduled jobs have been configured yet.",
  新增任务: "Create job",
  删除定时任务: "Delete scheduled job",
  执行定时任务: "Run scheduled job",
  立即执行: "Run immediately",
  定时任务操作: "Scheduled job actions",
  执行: "Run",
  日志: "Logs",
  执行一次: "Run once",
  放弃执行: "Skip run",
  禁止并发: "Disallow overlap",
  允许并发: "Allow overlap",
  清理任务日志: "Clean job logs",
  空任务: "No-op job",
  "执行后台依赖健康检查。": "Run a backend dependency health check.",
  "清理 30 天前的任务执行日志。":
    "Clean task execution logs older than 30 days.",
  任务名称: "Job name",
  调用目标: "Invoke target",
  执行表达式: "Cron expression",
  错过策略: "Misfire policy",
  并发: "Concurrency",
  执行编号: "Run ID",
  触发方式: "Trigger",
  执行消息: "Run message",
  开始时间: "Started at",
  结束时间: "Ended at",
  耗时: "Duration",
  手动: "Manual",
  自动: "Schedule",
  空任务已完成: "No-op job completed",
  健康检查通过: "Health check passed",
  健康检查失败: "Health check failed",
  任务日志清理失败: "Job log cleanup failed",
  "PostgreSQL 不可用": "PostgreSQL unavailable",
  不支持的调用目标: "Unsupported invoke target",
  "上一轮仍在执行，已跳过本次任务":
    "Previous run is still executing. This run was skipped.",
  "等待健康检查返回。": "Waiting for the health check response.",
  首页数据加载失败: "Failed to load home data",
  ok: "OK",
  unknown: "Unknown",

  个人信息: "Profile",
  修改密码: "Change password",
  账号设置: "Account settings",
  当前密码: "Current password",
  新密码: "New password",
  确认新密码: "Confirm password",
  密码强度: "Password strength",
  未输入: "Empty",
  偏弱: "Weak",
  一般: "Fair",
  较强: "Strong",
  清空: "Clear",
  保存密码: "Save password",
  上传头像: "Upload avatar",
  更换头像: "Change avatar",
  预览头像: "Preview avatar",
  复制用户名: "Copy username",
  保存资料: "Save profile",
  保存修改: "Save changes",
  重置: "Reset",
  提交: "Submit",
  从未: "Never",
  查看头像大图: "Preview avatar",
  "维护当前账号的头像、昵称和联系信息。":
    "Manage the avatar, nickname, and contact information for this account.",
  "头像、昵称和联系方式保存后立即生效。":
    "Avatar, nickname, and contact information take effect after saving.",
  "当前资料有修改，保存后会同步到当前账号。":
    "Profile changes will be synced to the current account after saving.",
  "当前资料已和服务器保持同步。":
    "Profile information is already in sync with the server.",
  账号信息已保存: "Account information saved",
  账号信息保存失败: "Failed to save account information",
  头像已更新: "Avatar updated",
  头像上传失败: "Failed to upload avatar",
  请选择jpgpngwebp或gif图片: "Select a jpg, png, webp, or gif image",
  "请选择 jpg、png、webp 或 gif 图片": "Select a jpg, png, webp, or gif image",
  "头像不能超过 5 MB": "Avatar must be 5 MB or smaller",
  暂无可复制的用户名: "No username to copy",
  用户名已复制: "Username copied",
  复制失败请稍后重试: "Copy failed. Try again later.",
  "复制失败，请稍后重试": "Copy failed. Try again later.",
  昵称不能为空: "Nickname is required",
  "昵称不能超过 64 个字符": "Nickname cannot exceed 64 characters",
  邮箱格式不正确: "Invalid email address",
  "手机号不能超过 32 个字符": "Phone number cannot exceed 32 characters",
  "头像地址不能超过 255 个字符": "Avatar URL cannot exceed 255 characters",
  请输入当前密码: "Enter current password",
  "新密码至少需要 10 位": "New password must be at least 10 characters",
  "新密码不能超过 128 位": "New password cannot exceed 128 characters",
  请再次输入新密码: "Confirm the new password",
  两次输入的新密码不一致: "The new passwords do not match",
  新密码不能和当前密码相同:
    "The new password cannot be the same as the current password",
  登录密码已更新: "Password updated",
  密码修改失败: "Failed to change password",
  "修改后请使用新密码登录当前账号。":
    "Use the new password next time you sign in to this account.",
  "至少 10 位，建议包含大小写字母、数字或符号。":
    "Use at least 10 characters. Uppercase, lowercase, numbers, or symbols are recommended.",
  "保存后服务端会校验当前密码是否正确。":
    "The server will verify the current password when saving.",
  隐藏密码: "Hide password",
  显示密码: "Show password",
  "输入新密码后显示强度。":
    "Password strength appears after you enter a new password.",
  建议至少10位并加入大小写数字或符号:
    "Use at least 10 characters and add letter case, numbers, or symbols.",
  "建议至少 10 位，并加入大小写、数字或符号。":
    "Use at least 10 characters and add letter case, numbers, or symbols.",
  "可以继续增加长度或更多字符类型。":
    "Add more length or character types to improve it.",
  强度不错继续增加长度会更稳: "Good strength. More length makes it safer.",
  "强度不错，继续增加长度会更稳。":
    "Good strength. More length makes it safer.",
  强度良好请妥善保存新密码: "Strong password. Keep it safe.",
  "强度良好，请妥善保存新密码。": "Strong password. Keep it safe.",
  强: "Strong",
  修改头像: "Change avatar",
  选择图片后裁剪为方形头像提交后才会上传:
    "Crop the image into a square avatar. It uploads only after submission.",
  "选择图片后裁剪为方形头像，提交后才会上传。":
    "Crop the image into a square avatar. It uploads only after submission.",
  待裁剪头像: "Avatar to crop",
  请选择图片: "Select an image",
  请选择头像图片: "Select an avatar image",
  缩小: "Zoom out",
  头像缩放: "Avatar zoom",
  放大: "Zoom in",
  选择图片: "Select image",
  头像预览: "Avatar preview",
  预览: "Preview",
  拖动图片调整位置使用缩放控制头像范围:
    "Drag the image to adjust position and use zoom to control the avatar area.",
  "拖动图片调整位置，使用缩放控制头像范围。":
    "Drag the image to adjust position and use zoom to control the avatar area.",
  头像图片加载失败: "Failed to load avatar image",
  当前浏览器不支持头像裁剪: "This browser does not support avatar cropping",
  头像裁剪失败: "Failed to crop avatar",
  "{title} 的头像": "{title}'s avatar",
}
